apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: chatflow
  labels:
    app: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi    # 5GB for AI models
  # storageClassName: gp2  # Uncomment for AWS EKS